# Data

In [1]:
import json

with open('data/result.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [2]:
import pandas as pd

df = pd.DataFrame(data['messages'])

In [3]:
from utils import preprocess_df

df = preprocess_df(df)

Загружено сообщений для анализа: 32738

# Pipeline

In [4]:
import numpy as np
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
embeddings = model.encode(df['clean_text'].tolist(), show_progress_bar=True)
# np.save('embeddings.npy', embeddings)

# embeddings = np.load('embeddings.npy')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/1024 [00:00<?, ?it/s]

In [21]:
from sklearn.cluster import KMeans

model = KMeans(n_clusters=100, random_state=42)
df['cluster'] = model.fit_predict(embeddings)

# Analysis

In [22]:
df

,date,text,from_id,clean_text,cluster
3,2025-08-01 03:16:34,Какое у него тупое еблище,user1547888108,Какое у него тупое еблище,44
4,2025-08-01 03:16:36,Зацените,user1547888108,Зацените,38
7,2025-08-01 07:13:31,Доброе утро мальчики,user1547888108,Доброе утро мальчики,20
8,2025-08-01 07:23:09,Невозможно,user818491332,Невозможно,68
9,2025-08-01 07:23:49,Virgin whiskers,user818491332,Virgin whiskers,43
...,...,...,...,...,...
42690,2026-01-31 17:30:21,пиздец,user492985890,пиздец,32
42691,2026-01-31 18:05:07,марк ты вообще мудак что ли.,user5386481314,марк ты вообще мудак что ли.,19
42692,2026-01-31 18:14:58,ты даже в нерабочее время на страже я смотрю,user492985890,ты даже в нерабочее время на страже я смотрю,61
42694,2026-01-31 20:37:21,шмальdestroyer,user877035234,шмальdestroyer,38
42696,2026-01-31 23:27:05,Бутират,user1547888108,Бутират,38

In [23]:
df[df['cluster'] == 10]

,date,text,from_id,clean_text,cluster
626,2025-08-03 09:36:39,воскресенье,user1022362005,воскресенье,10
2291,2025-08-05 21:25:58,Я ж завтра обоссусь на работе,user504205664,Я ж завтра обоссусь на работе,10
4526,2025-08-06 12:38:32,Крч завтра я точно нормик буду,user1547888108,Крч завтра я точно нормик буду,10
4543,2025-08-06 12:39:41,Я сегодня много че скину,user1547888108,Я сегодня много че скину,10
4547,2025-08-06 12:39:53,День контента намечается,user697756135,День контента намечается,10
...,...,...,...,...,...
41452,2026-01-20 10:17:01,Я сегодня на таком,user5386481314,Я сегодня на таком,10
41467,2026-01-20 10:35:04,не сегодня сеттиш,user1022362005,не сегодня сеттиш,10
41647,2026-01-22 15:44:24,Какой бы хуевый день ни был,user5386481314,Какой бы хуевый день ни был,10
41792,2026-01-24 13:45:36,День свободен,user881978429,День свободен,10
41834,2026-01-24 18:14:28,"отдыхаю, а вы чем заняты?",user492985890,"отдыхаю, а вы чем заняты?",10

In [24]:
df['cluster'].value_counts().describe()

count     100.000000
mean      327.380000
std       247.066579
min        38.000000
25%       162.750000
50%       264.000000
75%       460.000000
max      1350.000000
Name: count, dtype: float64