# Data

In [1]:
import json

with open('data/result.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [2]:
import pandas as pd

df = pd.DataFrame(data['messages'])

In [3]:
from utils import preprocess_df

df = preprocess_df(df)

Загружено сообщений для анализа: 32738

# Pipeline

In [4]:
import numpy as np
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
embeddings = model.encode(df['clean_text'].tolist(), show_progress_bar=True)
# np.save('embeddings.npy', embeddings)

# embeddings = np.load('embeddings.npy')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/1024 [00:00<?, ?it/s]

In [5]:
from sklearn.cluster import HDBSCAN

clusterer = HDBSCAN()
df['cluster'] = clusterer.fit_predict(embeddings)

C:\Users\nikol\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\cluster\_hdbscan\hdbscan.py:722: FutureWarning: The default value of `copy` will change from False to True in 1.10. Explicitly set a value for `copy` to silence this warning.
  warn(

# Analysis

In [6]:
df

,date,text,from_id,clean_text,cluster
3,2025-08-01 03:16:34,Какое у него тупое еблище,user1547888108,Какое у него тупое еблище,-1
4,2025-08-01 03:16:36,Зацените,user1547888108,Зацените,264
7,2025-08-01 07:13:31,Доброе утро мальчики,user1547888108,Доброе утро мальчики,-1
8,2025-08-01 07:23:09,Невозможно,user818491332,Невозможно,-1
9,2025-08-01 07:23:49,Virgin whiskers,user818491332,Virgin whiskers,-1
...,...,...,...,...,...
42690,2026-01-31 17:30:21,пиздец,user492985890,пиздец,423
42691,2026-01-31 18:05:07,марк ты вообще мудак что ли.,user5386481314,марк ты вообще мудак что ли.,-1
42692,2026-01-31 18:14:58,ты даже в нерабочее время на страже я смотрю,user492985890,ты даже в нерабочее время на страже я смотрю,-1
42694,2026-01-31 20:37:21,шмальdestroyer,user877035234,шмальdestroyer,-1
42696,2026-01-31 23:27:05,Бутират,user1547888108,Бутират,-1

In [10]:
len(df[df['cluster'] == -1])

28631

In [8]:
df['cluster'].value_counts().describe()

count      470.000000
mean        69.655319
std       1320.255821
min          5.000000
25%          6.000000
50%          7.000000
75%         10.000000
max      28631.000000
Name: count, dtype: float64

In [12]:
df[df['cluster'] == 468]

                    date    text         from_id clean_text  cluster
1893 2025-08-05 16:06:34  воркаю   user877035234     воркаю      468
1989 2025-08-05 16:11:01  воркаю  user6444735563     воркаю      468
2235 2025-08-05 21:17:39  воркаю  user6444735563     воркаю      468
2358 2025-08-05 21:31:25  воркаю  user6444735563     воркаю      468
2441 2025-08-05 21:37:28  воркаю  user6444735563     воркаю      468
2707 2025-08-06 09:49:09  воркаю  user6444735563     воркаю      468
7323 2025-08-07 15:40:29  воркаю  user6444735563     воркаю      468

In [14]:
df[df['cluster'] == 448]

                     date         text        from_id   clean_text  cluster
2388  2025-08-05 21:33:32  А вот такое  user504205664  А вот такое      448
5443  2025-08-06 14:36:36  Вот так вот  user877035234  Вот так вот      448
5896  2025-08-06 16:48:52  вот так вот  user877035234  вот так вот      448
6050  2025-08-06 17:14:33  Вот так вот  user881978429  Вот так вот      448
6939  2025-08-07 11:04:54  Вот так вот  user877035234  Вот так вот      448
7010  2025-08-07 11:26:49  Вот так вот  user877035234  Вот так вот      448
9269  2025-08-11 12:03:38  Вот так вот  user877035234  Вот так вот      448
24076 2025-10-17 15:46:00    А вот это  user504205664    А вот это      448
24400 2025-10-19 18:52:37      Вот это  user881978429      Вот это      448
33100 2025-12-05 07:37:59  вот так вот  user492985890  вот так вот      448

ахаха differnces

In [11]:
df[df['cluster'] == 465]

                     date      text         from_id clean_text  cluster
8149  2025-08-08 12:26:03  АХАХАХАХ   user504205664   АХАХАХАХ      465
9130  2025-08-11 09:37:56  АХАХАХАХ  user5386481314   АХАХАХАХ      465
10168 2025-08-14 12:35:49  АХАХАХАХ  user5386481314   АХАХАХАХ      465
28372 2025-11-05 15:20:23  АХАХАХАХ  user5386481314   АХАХАХАХ      465
38338 2025-12-25 11:29:29  АХАХАХАХ  user5386481314   АХАХАХАХ      465

In [13]:
df[df['cluster'] == 464]

                     date          text         from_id    clean_text  cluster
10496 2025-08-15 11:48:55    АХАХАХАХАХ  user5386481314    АХАХАХАХАХ      464
22723 2025-10-14 12:41:40      АХАХАХАА  user5386481314      АХАХАХАА      464
22749 2025-10-14 12:44:41    АХАХАХАХАХ   user504205664    АХАХАХАХАХ      464
26675 2025-10-28 12:56:36      АХАХАХАА  user5386481314      АХАХАХАА      464
26676 2025-10-28 12:56:37    АХАХАХАХАХ  user5386481314    АХАХАХАХАХ      464
28371 2025-11-05 15:20:20  АХАХАХАХАХАХ  user5386481314  АХАХАХАХАХАХ      464